In [1]:
#importing pandas
import pandas as pd

In [9]:
#importing the CSV file
df = pd.read_csv('bmwsales.csv')

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Model                 50000 non-null  str
 1   Year                  50000 non-null  int64
 2   Region                50000 non-null  str
 3   Color                 50000 non-null  str
 4   Fuel_Type             50000 non-null  str
 5   Transmission          50000 non-null  str
 6   Engine_Size_L         50000 non-null  float64
 7   Mileage_KM            50000 non-null  int64
 8   Price_USD             50000 non-null  int64
 9   Sales_Volume          50000 non-null  int64
 10  Sales_Classification  50000 non-null  str
dtypes: float64(1), int64(4), str(6)
memory usage: 4.2 MB

In [11]:
df.head()

,Model,Year,Region,Color,Fuel_Type,Transmission,Engine_Size_L,Mileage_KM,Price_USD,Sales_Volume,Sales_Classification
0,5 Series,2016,Asia,Red,Petrol,Manual,3.5,151748,98740,8300,High
1,i8,2013,North America,Red,Hybrid,Automatic,1.6,121671,79219,3428,Low
2,5 Series,2022,North America,Blue,Petrol,Automatic,4.5,10991,113265,6994,Low
3,X3,2024,Middle East,Blue,Petrol,Automatic,1.7,27255,60971,4047,Low
4,7 Series,2020,South America,Black,Diesel,Manual,2.1,122131,49898,3080,Low

In [17]:
df.columns

Index(['Model', 'Year', 'Region', 'Color', 'Fuel_Type', 'Transmission',
       'Engine_Size_L', 'Mileage_KM', 'Price_USD', 'Sales_Volume',
       'Sales_Classification'],
      dtype='str')

In [18]:
df.shape

(50000, 11)

In [19]:
df.describe()

               Year  Engine_Size_L     Mileage_KM      Price_USD  Sales_Volume
count  50000.000000   50000.000000   50000.000000   50000.000000  50000.000000
mean    2017.015700       3.247180  100307.203140   75034.600900   5067.514680
std        4.324459       1.009078   57941.509344   25998.248882   2856.767125
min     2010.000000       1.500000       3.000000   30000.000000    100.000000
25%     2013.000000       2.400000   50178.000000   52434.750000   2588.000000
50%     2017.000000       3.200000  100388.500000   75011.500000   5087.000000
75%     2021.000000       4.100000  150630.250000   97628.250000   7537.250000
max     2024.000000       5.000000  199996.000000  119998.000000   9999.000000

In [20]:
df.isnull().sum()

Model                   0
Year                    0
Region                  0
Color                   0
Fuel_Type               0
Transmission            0
Engine_Size_L           0
Mileage_KM              0
Price_USD               0
Sales_Volume            0
Sales_Classification    0
dtype: int64

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
df['Model'].unique()

<StringArray>
['5 Series',       'i8',       'X3', '7 Series',       'M5', '3 Series',
       'X1',       'M3',       'X5',       'i3',       'X6']
Length: 11, dtype: str

In [23]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [24]:
df.columns

Index(['model', 'year', 'region', 'color', 'fuel_type', 'transmission',
       'engine_size_l', 'mileage_km', 'price_usd', 'sales_volume',
       'sales_classification'],
      dtype='str')

In [25]:
print(df['year'].value_counts().sort_index())

year
2010    3330
2011    3278
2012    3332
2013    3326
2014    3350
2015    3358
2016    3365
2017    3290
2018    3278
2019    3392
2020    3205
2021    3372
2022    3478
2023    3219
2024    3427
Name: count, dtype: int64

In [26]:
df['revenue_usd'] = df['price_usd'] * df['sales_volume']

In [27]:
df.columns

Index(['model', 'year', 'region', 'color', 'fuel_type', 'transmission',
       'engine_size_l', 'mileage_km', 'price_usd', 'sales_volume',
       'sales_classification', 'revenue_usd'],
      dtype='str')

In [28]:
df.to_csv('bmwsales.csv', index=False)